# Generated by Django 4.2.7 on 2025-04-16 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('vietcombank', 'Vietcombank'), ('techcombank', 'Techcombank'), ('bidv', 'BIDV'), ('vietinbank', 'Vietinbank'), ('mbbank', 'MB Bank'), ('tpbank', 'TPBank'), ('acb', 'ACB'), ('sacombank', 'Sacombank'), ('vpbank', 'VPBank'), ('other', 'Ngân hàng khác')], max_length=100, verbose_name='Tên ngân hàng')),
                ('other_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên ngân hàng khác')),
                ('account_name', models.CharField(max_length=255, verbose_name='Tên chủ tài khoản')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi nhánh')),
                ('is_default', models.BooleanField(default=False, verbose_name='Là tài khoản mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ví điện tử',
                'verbose_name_plural': 'Ví điện tử',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền')], max_length=10, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí giao dịch')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thực nhận/thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('vnpay', 'VNPay'), ('other', 'Khác')], max_length=50, verbose_name='Phương thức thanh toán')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tham chiếu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portfolio.bankaccount', verbose_name='Tài khoản ngân hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.wallet')),
            ],
            options={
                'verbose_name': 'Giao dịch ví điện tử',
                'verbose_name_plural': 'Giao dịch ví điện tử',
                'indexes': [models.Index(fields=['user'], name='portfolio_w_user_id_635388_idx'), models.Index(fields=['wallet'], name='portfolio_w_wallet__8161fe_idx'), models.Index(fields=['type'], name='portfolio_w_type_ff4dda_idx'), models.Index(fields=['status'], name='portfolio_w_status_7e395f_idx'), models.Index(fields=['transaction_id'], name='portfolio_w_transac_c7f850_idx'), models.Index(fields=['created_at'], name='portfolio_w_created_2359b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user'], name='portfolio_b_user_id_541073_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number'], name='portfolio_b_account_ed6ace_idx'),
        ),
    ]
